const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict'), path = require('node:path');
const elements = new Map(), storage = new Map(); let failStorage = false;
const el = () => ({style:{},dataset:{},value:'',classList:{add(){},remove(){},toggle(){}},setAttribute(){},scrollIntoView(){},addEventListener(){},querySelector(){return el()},querySelectorAll(){return []},appendChild(){},focus(){},showModal(){this.open=true},close(){this.open=false}});
const context = {window:{},document:{getElementById(id){if(!elements.has(id))elements.set(id,el());return elements.get(id)},querySelector:el,querySelectorAll(){return []},createElement:el},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>{if(failStorage)throw new Error('quota');storage.set(k,v)}},setTimeout(){},clearTimeout(){},Date,Math,console};
vm.createContext(context);
const source = fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');
const expose = 'globalThis.game={blankState,migrateState,loadState,saveSlot,loadSlot,trainSkill,performInteraction,continueStory,resolveChoice,mainEventReady,openPractice,combatTurn,events,mainSideRequirements,getEventById,runFreeAction,travelTo,dailyAction,buyItem,learnTalent,talentPoints,tutorialGoals,sideQuests,claimTutorial,questAction,questProgress,grantReward,applyLivingCost,validateSave,saveEnvelope,previewImport,confirmImport,get state(){return state},set state(v){state=v}};';
vm.runInContext(source.replace(/  openStart\(\);\r?\n\}\)\(\);/,expose+'\n})();'),context);
const g = context.game, profile = {name:'测试旅人',identity:'转生者',race:'人族',timeline:'childhood',location:'布艾纳村',goal:'magic'};
const fresh = () => (g.state=g.blankState({...profile})), clone = x => JSON.parse(JSON.stringify(x));
const key = 'six-faced-life.autosave.v1'; let s;
for (const version of [1,2,3,4]) {
 const old=clone(fresh()); old.version=version; old.turn=17;old.relations={'洛琪希':24};old.seen=['transfer_calamity'];delete old.quests;old.tutorial={actions:['train']};
 if(version<4)for(const field of ['survival','equipment','inventory','talents','regionalReputation','encounterCount','progression','story'])delete old[field];
 else old.survival.food=0;
 g.loadState(old);s=g.state;assert.equal(s.version,5);assert.equal(s.relations['洛琪希'],24);assert.equal(s.turn,17);assert(!('food' in s.survival));assert.equal(JSON.parse(storage.get(key)).version,5);
 assert(g.claimTutorial('train'));assert(s.inventory.ownedEquipment.includes('novice_sword'));g.loadState(clone(s));assert(!g.claimTutorial('train'));g.validateSave(s);
}
s=fresh();g.trainSkill('water_ball','magic');assert.equal(s.skills.water_ball,27);assert.equal(s.money,11);assert.equal(s.resumeEventId,'opening');assert(!('food' in s.survival));g.continueStory();assert.equal(s.currentEventId,'opening');
s.money=0;const before=clone(s);g.trainSkill('water_ball','magic');assert.deepEqual(clone(s),before);g.dailyAction('work');assert(s.money>0);g.dailyAction('forage');assert.equal(s.inventory.medicine,1);
s.survival.fatigue=100;g.dailyAction('rest');assert.equal(s.survival.fatigue,40);g.runFreeAction('使用药品');assert.equal(s.inventory.medicine,0);assert.equal(s.survival.fatigue,15);
s=fresh();assert(!g.claimTutorial('choice'));assert(!g.questAction('guild_helper','accept'));g.resolveChoice(g.getEventById('opening').choices[0],0);const xp=s.progression.xp;assert(g.claimTutorial('choice'));assert.equal(s.progression.xp,xp+12);const claimed=clone(s);assert(!g.claimTutorial('choice'));assert.deepEqual(clone(s),claimed);
g.dailyAction('work');g.questAction('guild_helper','accept');const helper=g.sideQuests.find(q=>q.id==='guild_helper');assert.equal(g.questProgress(helper),0);assert(!g.questAction(helper.id,'claim'));g.dailyAction('work');assert.equal(g.questProgress(helper),1);g.questAction(helper.id,'abandon');g.questAction(helper.id,'accept');assert.equal(g.questProgress(helper),0);
g.dailyAction('work');g.dailyAction('work');assert.equal(g.questProgress(helper),2);const money=s.money;assert(g.questAction(helper.id,'claim'));assert.equal(s.money,money+15);assert(!g.questAction(helper.id,'claim'));assert(!g.questAction(helper.id,'accept'));assert(!g.questAction(helper.id,'abandon'));g.loadState(clone(s));assert(!g.questAction(helper.id,'claim'));
for(const quest of g.sideQuests){s=fresh();s.tutorial.claimed=['choice'];assert(g.questAction(quest.id,'accept'));s.quests.counters[quest.counter]+=quest.need;assert(g.questAction(quest.id,'claim'));assert(!g.questAction(quest.id,'claim'));g.validateSave(s);}
s=fresh();s.tutorial.actions=['choice','train','bond','travel','save'];for(const goal of g.tutorialGoals)assert(g.claimTutorial(goal.id));assert.equal(s.progression.xp,128);assert(s.tutorial.claimed.includes('graduation'));assert(s.inventory.ownedEquipment.includes('mage_staff'));const graduated=clone(s);for(const goal of g.tutorialGoals)assert(!g.claimTutorial(goal.id));assert.deepEqual(clone(s),graduated);
s=fresh();s.money=100;g.buyItem('iron_sword');g.grantReward({equipment:'novice_sword'});assert.equal(s.equipment.bonuses.weapon,3);assert(s.inventory.ownedEquipment.includes('novice_sword'));
s=fresh();g.saveSlot(0);assert(s.tutorial.actions.includes('save'));g.dailyAction('work');g.loadSlot(0);assert.equal(g.state.money,12);assert.equal(g.state.version,5);assert(g.state.tutorial.actions.includes('save'));
s=fresh();failStorage=true;g.saveSlot(1);assert(!s.tutorial.actions.includes('save'));failStorage=false;
s=fresh();s.progression.xp=180;g.learnTalent('silent_cast');assert.equal(s.talents.length,0);g.learnTalent('mana_control');g.learnTalent('element_fire');g.learnTalent('silent_cast');assert.equal(g.talentPoints(),0);assert.equal(s.skills.fire_ball,10);
s=fresh();g.runFreeAction('练习火魔法');assert.equal(s.skills.fire_ball,undefined);assert(s.lastResult.includes('火系研究'));g.runFreeAction('练习水神流格挡');assert.equal(s.progression.swordStyles.waterGod,6);
s=fresh();s.skills.healing=10;s.equipment.bonuses.focus=3;g.openPractice();const enemy=s.combat.enemy;g.combatTurn('healing');assert.equal(s.combat.enemy,enemy);const fatigue=s.survival.fatigue;g.openPractice();assert.equal(s.survival.fatigue,fatigue);s.combat.enemy=1;g.combatTurn('arm_drop');assert.equal(s.quests.counters.victory,1);assert.equal(s.combat,null);g.continueStory();assert.equal(s.currentEventId,'opening');
s=fresh();s.money=100;s.unlockedLocations.push('魔大陆');g.travelTo('魔大陆');assert.equal(s.location,'魔大陆');assert.equal(s.encounterCount,1);assert.equal(s.quests.counters.travel,1);assert(!('food' in s.survival));s.talents=['field_lore'];s.equipment.armor='防雨旅行斗篷';s.survival.fatigue=0;g.applyLivingCost(5,4,'travel');assert.equal(s.survival.fatigue,0);
for(const [id,need] of Object.entries(g.mainSideRequirements)){s=fresh();const e=g.events.find(e=>e.id===id);s.story.sideSinceMain=need-1;assert(!g.mainEventReady(e));s.story.sideSinceMain++;assert(g.mainEventReady(e));}
s=fresh();const envelope=clone(g.saveEnvelope());s.secretToken='must not export';s.profile.password='must not export';assert(!JSON.stringify(g.saveEnvelope()).includes('must not export'));s=fresh();g.dailyAction('work');const previous=clone(s);g.previewImport(envelope,'测试');assert.equal(g.state.money,previous.money);failStorage=true;assert(!g.confirmImport());assert.equal(g.state.money,previous.money);failStorage=false;assert(g.confirmImport());assert.equal(g.state.money,12);const recovery=JSON.parse(storage.get('six-faced-life.before-import.v1'));assert.equal(recovery.state.money,previous.money);
for(const mutate of [x=>x.stats.mana='bad',x=>x.version=99,x=>x.profile.goal='oops',x=>x.progression.xp=null,x=>x.tutorial.claimed='wrong',x=>x.history=[{}],x=>x.quests.counters.work=-1,x=>x.quests.records={guild_helper:{start:-1}},x=>x.inventory.medicine=-1,x=>x.survival.fatigue=999]){const bad=clone(envelope.state);mutate(bad);assert.throws(()=>g.validateSave(bad));}
assert.throws(()=>g.validateSave(JSON.parse('{"__proto__":{"polluted":true}}')));assert.throws(()=>g.previewImport({format:'text',state:envelope.state},'错误'));
s=fresh();s.survival.fatigue=100;const restBaseline=clone(s);g.dailyAction('rest');assert.equal(s.survival.fatigue,40);assert.equal(s.ageMonths,restBaseline.ageMonths);assert.equal(s.ageDays,1);assert.equal(s.story.sideSinceMain,restBaseline.story.sideSinceMain);assert.equal(s.progression.xp,restBaseline.progression.xp);assert.equal(s.money,restBaseline.money);g.dailyAction('rest');assert.equal(s.survival.fatigue,0);assert.equal(s.ageDays,2);g.loadState(clone(s));s=g.state;assert.equal(s.ageDays,2);s.ageDays=29;g.dailyAction('rest');assert.equal(s.ageMonths,restBaseline.ageMonths+1);assert.equal(s.ageDays,0);s.ageDays=7;g.previewImport(g.saveEnvelope(),'天数');g.confirmImport();assert.equal(g.state.ageDays,7);const legacyDays=clone(g.state);delete legacyDays.ageDays;g.loadState(legacyDays);assert.equal(g.state.ageDays,0);assert.throws(()=>g.validateSave({...g.state,ageDays:30}));
s=fresh();g.openPractice();const withCombat=clone(g.saveEnvelope());assert(withCombat.state.combat);g.previewImport(withCombat,'对练');assert(g.confirmImport());assert(g.state.combat);
s=fresh();s.relations['洛琪希']=19;g.performInteraction('洛琪希','talk');assert(s.bondMemories.includes('洛琪希:20'));assert.equal(s.quests.counters.bond,1);const bondSave=g.saveEnvelope();g.previewImport(bondSave,'羁绊');g.confirmImport();assert(g.state.bondMemories.includes('洛琪希:20'));g.performInteraction('洛琪希','talk');assert.equal(g.state.bondMemories.filter(x=>x==='洛琪希:20').length,1);
s=fresh();for(let i=0;i<300;i++){
 if(s.survival.fatigue>65)g.dailyAction('rest');else if(s.money<3)g.dailyAction('work');else if(i%3===0)g.trainSkill('water_ball','magic');else {g.continueStory();const event=g.getEventById(s.currentEventId);g.resolveChoice(event.choices.find(c=>!c.requires||c.requires(s)),0);}
 assert(s.money>=0);assert(!('food' in s.survival));assert(s.survival.fatigue>=0&&s.survival.fatigue<=100);assert(Object.values(s.stats).every(n=>Number.isFinite(n)&&n>=0&&n<=100));g.validateSave(s);
}
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const match of source.matchAll(/\$\("([^"]+)"\)/g))assert(ids.includes(match[1]),`Missing DOM id ${match[1]}`);
if(process.env.QA_FIXTURE_DIR){s=fresh();fs.writeFileSync(path.join(process.env.QA_FIXTURE_DIR,'save-v5-fixture.json'),JSON.stringify(g.saveEnvelope(),null,2));s.survival.fatigue=100;fs.writeFileSync(path.join(process.env.QA_FIXTURE_DIR,'rest-v5-fixture.json'),JSON.stringify(g.saveEnvelope(),null,2));}
console.log('PASS v5: legacy migrations, no-food economy, tutorial rewards, all 6 side quests, repeat-claim guards, talents, combat, travel, main pacing, save validation/recovery/storage failure, DOM IDs, 300 turns');
